#!/usr/bin/env python3
"""
build-partners.py - Render Taranis Capital strategic-partner cards from data.

Usage:
    python tools/build-partners.py            # rewrite the partner cards
    python tools/build-partners.py --check    # verify pages are in sync (CI)

Reads taranis-partners-data.json and rewrites the partner cards between the
<!-- PARTNERS:START --> ... <!-- PARTNERS:END --> markers on:

    who-we-are.html                       (main site - one card per partner
                                            where mainSite.shown, by mainSite.order)
    subdomains/<fund>/index.html           (one card per partner where
                                            funds.<fund>.shown)

Each fund entry may override brand (display name), url and description; a
blank/absent override falls back to the partner's main-site name/url/
description. This powers the Disrupts Media special case: one "Disrupts Media"
card on the main site, a different brand on each fund subdomain.

The script is idempotent - it only ever touches the marked card region, so
re-running after a data edit produces a clean diff. It also strips the stray
trailing NUL bytes that some of these pages carry from an earlier tool.

See docs/MANAGE-PARTNERS.md for the data format and full workflow.
"""

import argparse
import html
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DATA_FILE = REPO_ROOT / "taranis-partners-data.json"

# Fund key (as used in the JSON) -> subdomain page. Note the data key
# "disruptiveTech" maps to the "disruptive-tech" directory.
SUBDOMAIN_PAGES = {
    "fintech": REPO_ROOT / "subdomains" / "fintech" / "index.html",
    "biotech": REPO_ROOT / "subdomains" / "biotech" / "index.html",
    "datacentre": REPO_ROOT / "subdomains" / "datacentre" / "index.html",
    "property": REPO_ROOT / "subdomains" / "property" / "index.html",
    "disruptiveTech": REPO_ROOT / "subdomains" / "disruptive-tech" / "index.html",
}

MAIN_PAGE = REPO_ROOT / "who-we-are.html"

# Indentation of the card region on each page (markers sit at the same level).
MAIN_INDENT = "      "          # 6 spaces - inside the inline-style grid div
SUBDOMAIN_INDENT = "                "  # 16 spaces - inside .partners-grid

START_COMMENT = (
    "<!-- PARTNERS:START (generated by tools/build-partners.py from "
    "taranis-partners-data.json; edit the JSON, not this block) -->"
)
END_COMMENT = "<!-- PARTNERS:END -->"

# Matches the whole START..END block including each marker's leading indent.
MARKER_RE = re.compile(
    r"[ \t]*<!--\s*PARTNERS:START.*?-->.*?[ \t]*<!--\s*PARTNERS:END\s*-->",
    re.DOTALL,
)


def load_partners():
    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    return data["partners"]


def esc(text):
    """Escape a text node (leaves quotes/apostrophes and unicode intact)."""
    return html.escape(str(text), quote=False)


def esc_attr(value):
    """Escape an attribute value (href)."""
    return html.escape(str(value), quote=True)


def display_url(url):
    """Strip scheme, leading www. and trailing slash for the link label."""
    s = re.sub(r"^https?://", "", url.strip())
    s = re.sub(r"^www\.", "", s)
    return s.rstrip("/")


def resolve(partner, fund):
    """Resolve (title, url, description) for a partner on a given fund,
    applying the per-fund override with fallback to the main-site values."""
    entry = partner.get("funds", {}).get(fund, {})
    title = entry.get("brand") or partner["name"]
    url = entry.get("url") or partner["url"]
    description = entry.get("description") or partner["description"]
    return title, url, description


def sort_key(partner, title):
    """Ordering rule: the Disrupts Media group brand always renders first,
    then every other partner alphabetically by its displayed name/brand.
    (Per Mark's instruction, 9 Jun 2026 - supersedes the data's mainSite.order.)"""
    return (not partner.get("isGroup", False), title.casefold())


# --- card renderers ---------------------------------------------------------

def render_main_card(partner):
    i = MAIN_INDENT
    name = esc(partner["name"])
    url = esc_attr(partner["url"])
    desc = esc(partner["description"])
    return (
        f'{i}<a href="{url}" target="_blank" rel="noopener noreferrer" style="text-decoration:none;display:flex;">\n'
        f'{i}  <div style="background: white; border-radius: 8px; padding: 32px 24px; border: 1px solid var(--tc-grey-light); text-align: center; transition: box-shadow 0.3s ease, transform 0.3s ease; box-shadow: 0 2px 8px rgba(0,0,0,0.04); display:flex; flex-direction:column; justify-content:center; width:100%;">\n'
        f"{i}    <div style=\"font-family: 'Playfair Display', serif; font-size: 20px; color: var(--tc-charcoal); font-weight: 600; margin-bottom: 8px;\">{name}</div>\n"
        f'{i}    <div style="font-size: 14px; color: var(--tc-grey-dark);">{desc}</div>\n'
        f"{i}  </div>\n"
        f"{i}</a>"
    )


def render_subdomain_card(partner, fund):
    i = SUBDOMAIN_INDENT
    title, url, description = resolve(partner, fund)
    return (
        f'{i}<div class="partner-card">\n'
        f"{i}    <h3>{esc(title)}</h3>\n"
        f'{i}    <a href="{esc_attr(url)}" class="website" target="_blank" rel="noopener">{esc(display_url(url))}</a>\n'
        f"{i}    <p>{esc(description)}</p>\n"
        f"{i}</div>"
    )


# --- block assembly + file rewrite ------------------------------------------

def build_block(cards, indent):
    """Wrap rendered cards in the START/END markers at the given indent."""
    body = "\n".join(cards)
    return f"{indent}{START_COMMENT}\n{body}\n{indent}{END_COMMENT}"


def rewrite(path, block):
    """Replace the marked region in `path` with `block`. Returns (changed, new_text).
    Reads/normalises the file, strips trailing NULs, never touches anything
    outside the markers."""
    raw = path.read_text(encoding="utf-8")
    text = raw.replace("\r\n", "\n").rstrip("\x00")
    if not text.endswith("\n"):
        text += "\n"

    if not MARKER_RE.search(text):
        sys.exit(
            f"ERROR: PARTNERS:START/END markers not found in {path.relative_to(REPO_ROOT)}.\n"
            f"       Add the marker pair to the page before running this tool."
        )

    new_text = MARKER_RE.sub(lambda _m: block, text, count=1)
    changed = new_text.encode("utf-8") != raw.encode("utf-8")
    return changed, new_text


def validate(partners):
    """Light sanity checks on the data before rendering."""
    slugs = [p.get("slug") for p in partners]
    dupes = {s for s in slugs if slugs.count(s) > 1}
    if dupes:
        sys.exit(f"ERROR: duplicate partner slug(s) in data: {sorted(dupes)}")
    for p in partners:
        for field in ("slug", "name", "url", "description"):
            if not p.get(field):
                sys.exit(f"ERROR: partner '{p.get('slug', '?')}' missing required field '{field}'")
    # Invariant: at most one card per slug per subdomain (true by construction,
    # but guards against a future data shape that lists a slug twice).
    for fund in SUBDOMAIN_PAGES:
        shown = [p["slug"] for p in partners if p.get("funds", {}).get(fund, {}).get("shown")]
        if len(shown) != len(set(shown)):
            sys.exit(f"ERROR: duplicate partner on subdomain '{fund}': {shown}")


def main():
    parser = argparse.ArgumentParser(
        description="Render Taranis strategic-partner cards from taranis-partners-data.json."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify pages are already in sync; exit 1 if any would change (no writes).",
    )
    args = parser.parse_args()

    partners = load_partners()
    validate(partners)

    # Build every target's block first.
    targets = []  # (label, path, block, count)

    main_partners = sorted(
        (p for p in partners if p.get("mainSite", {}).get("shown")),
        key=lambda p: sort_key(p, p["name"]),
    )
    main_cards = [render_main_card(p) for p in main_partners]
    targets.append(("who-we-are.html", MAIN_PAGE, build_block(main_cards, MAIN_INDENT), len(main_cards)))

    for fund, path in SUBDOMAIN_PAGES.items():
        fund_partners = sorted(
            (p for p in partners if p.get("funds", {}).get(fund, {}).get("shown")),
            key=lambda p: sort_key(p, resolve(p, fund)[0]),
        )
        cards = [render_subdomain_card(p, fund) for p in fund_partners]
        label = str(path.relative_to(REPO_ROOT)).replace("\\", "/")
        targets.append((label, path, build_block(cards, SUBDOMAIN_INDENT), len(cards)))

    out_of_sync = []
    written = []
    for label, path, block, count in targets:
        changed, new_text = rewrite(path, block)
        if args.check:
            if changed:
                out_of_sync.append(label)
            print(f"  {'DRIFT ' if changed else 'ok    '} {label}  ({count} card{'s' if count != 1 else ''})")
        else:
            if changed:
                path.write_bytes(new_text.encode("utf-8"))
                written.append(label)
            print(f"  {'updated' if changed else 'nochange'}  {label}  ({count} card{'s' if count != 1 else ''})")

    print()
    if args.check:
        if out_of_sync:
            print(f"OUT OF SYNC: {len(out_of_sync)} page(s) would change. Run: python tools/build-partners.py")
            sys.exit(1)
        print("All partner sections are in sync with taranis-partners-data.json.")
        return

    if written:
        print("Stage with:")
        print("  git add taranis-partners-data.json " + " ".join(written))
    else:
        print("No changes - all pages already match taranis-partners-data.json.")


if __name__ == "__main__":
    main()
