#!/usr/bin/env python3
"""
build-people.py - Render Taranis Capital fund-team cards from data.

Usage:
    python tools/build-people.py            # rewrite the team cards
    python tools/build-people.py --check    # verify pages are in sync (CI)

Reads taranis-fund-teams.json (the roster) and rewrites the section-aware team
cards between the <!-- TEAM:START --> ... <!-- TEAM:END --> markers on each of
the five fund subdomains:

    subdomains/fintech/index.html
    subdomains/biotech/index.html
    subdomains/datacentre/index.html
    subdomains/property/index.html
    subdomains/disruptive-tech/index.html        (roster key "disruptiveTech")

The roster owns, per fund, the ordered sections and the ordered members in each,
with each member's curated title. Identity is resolved from
taranis-people-data.json by slug:

    name  = member.name  or  person.fullName
    image = person.profileImage.path            (no override; prefixed with the
                                                 site origin to match the cards)
    bio   = member.bio   or  person.funds[fund].bio
    title = member.title                        (always from the roster)
    alt   = the displayed name

A member.bio / member.name override is used only where the card must differ from
the directory - e.g. biotech's recurring people (Nicholas Bingham and Osama
Bukhari each appear in two sections with different bios), and the ~31 cards whose
curated bio has drifted from the directory's stale per-fund bio.

This is the section-aware sibling of tools/build-partners.py. It reuses that
tool's proven mechanics: a marker-bounded, idempotent rewrite that only ever
touches the marked region, strips stray trailing NUL bytes, and preserves each
page's existing newline style so the diff stays minimal on CRLF working trees.

See docs/MANAGE-PEOPLE-TEAMS.md for the data format and full workflow.
"""

import argparse
import html
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
ROSTER_FILE = REPO_ROOT / "taranis-fund-teams.json"
PEOPLE_FILE = REPO_ROOT / "taranis-people-data.json"

# Roster fund key (as used in the JSON) -> subdomain page. The data key
# "disruptiveTech" maps to the "disruptive-tech" directory (as in build-partners.py).
SUBDOMAIN_PAGES = {
    "fintech": REPO_ROOT / "subdomains" / "fintech" / "index.html",
    "biotech": REPO_ROOT / "subdomains" / "biotech" / "index.html",
    "datacentre": REPO_ROOT / "subdomains" / "datacentre" / "index.html",
    "property": REPO_ROOT / "subdomains" / "property" / "index.html",
    "disruptiveTech": REPO_ROOT / "subdomains" / "disruptive-tech" / "index.html",
}

# Absolute origin the existing team-card <img> tags use.
IMG_ORIGIN = "https://taraniscapital.com"

# Indentation of the team region (observed in the live pages; confirmed before
# finalising, as build-partners.py learned with its two different indents):
#   team-section-title / team-grid   -> 12 spaces (markers sit here too)
#   team-member                      -> 16 spaces
#   the card's inner elements        -> 20 spaces
I12 = " " * 12
I16 = " " * 16
I20 = " " * 20

START_COMMENT = (
    "<!-- TEAM:START (generated by tools/build-people.py from "
    "taranis-fund-teams.json; edit the JSON, not this block) -->"
)
END_COMMENT = "<!-- TEAM:END -->"

# Matches the whole START..END block including each marker's leading indent.
MARKER_RE = re.compile(
    r"[ \t]*<!--\s*TEAM:START.*?-->.*?[ \t]*<!--\s*TEAM:END\s*-->",
    re.DOTALL,
)


def load_roster():
    return json.loads(ROSTER_FILE.read_text(encoding="utf-8"))["funds"]


def load_people():
    data = json.loads(PEOPLE_FILE.read_text(encoding="utf-8"))
    return {p["slug"]: p for p in data["people"]}


def esc(text):
    """Escape a text node (leaves quotes/apostrophes and unicode intact)."""
    return html.escape(str(text), quote=False)


def esc_attr(value):
    """Escape an attribute value (src, alt)."""
    return html.escape(str(value), quote=True)


def resolve(member, person, fund):
    """Resolve (name, image, title, bio) for a roster member, applying the
    per-member override with fallback to the person directory."""
    name = member.get("name") or person["fullName"]
    image = person["profileImage"]["path"]
    title = member["title"]
    bio = member.get("bio") or person.get("funds", {}).get(fund, {}).get("bio") or ""
    return name, image, title, bio


# --- card / section renderers -----------------------------------------------

def render_member(member, person, fund):
    name, image, title, bio = resolve(member, person, fund)
    src = f"{IMG_ORIGIN}{image}"
    return (
        f'{I16}<div class="team-member">\n'
        f'{I20}<img src="{esc_attr(src)}" alt="{esc_attr(name)}">\n'
        f"{I20}<h3>{esc(name)}</h3>\n"
        f'{I20}<p class="title">{esc(title)}</p>\n'
        f"{I20}<p>{esc(bio)}</p>\n"
        f"{I16}</div>"
    )


def render_section(section, people, fund):
    cards = [render_member(m, people[m["slug"]], fund) for m in section["members"]]
    return (
        f'{I12}<div class="team-section-title">{esc(section["title"])}</div>\n'
        f'{I12}<div class="team-grid">\n'
        + "\n".join(cards)
        + f"\n{I12}</div>"
    )


def build_block(fund_data, people, fund):
    """Wrap the rendered sections in the START/END markers. Sections are
    separated by a single blank line, matching the live pages."""
    body = "\n\n".join(render_section(s, people, fund) for s in fund_data["sections"])
    return f"{I12}{START_COMMENT}\n{body}\n{I12}{END_COMMENT}"


# --- file rewrite -----------------------------------------------------------

def rewrite(path, block):
    """Replace the marked region in `path` with `block`. Returns (changed, out_bytes).
    Reads/normalises the file, strips trailing NULs, preserves the file's existing
    newline style, and never touches anything outside the markers."""
    raw = path.read_text(encoding="utf-8")
    newline = "\r\n" if "\r\n" in raw else "\n"
    text = raw.replace("\r\n", "\n").rstrip("\x00")
    if not text.endswith("\n"):
        text += "\n"

    if not MARKER_RE.search(text):
        sys.exit(
            f"ERROR: TEAM:START/END markers not found in {path.relative_to(REPO_ROOT)}.\n"
            f"       Add the marker pair to the page before running this tool\n"
            f"       (immediately before the first <div class=\"team-section-title\">\n"
            f"       and immediately after the final team-grid </div>)."
        )

    new_text = MARKER_RE.sub(lambda _m: block, text, count=1)
    if newline == "\r\n":
        new_text = new_text.replace("\n", "\r\n")
    out = new_text.encode("utf-8")
    changed = out != raw.encode("utf-8")
    return changed, out


def validate(roster, people):
    """Sanity checks on the roster before rendering."""
    for fund, fund_data in roster.items():
        if fund not in SUBDOMAIN_PAGES:
            sys.exit(f"ERROR: unknown fund key '{fund}' in roster (expected one of {list(SUBDOMAIN_PAGES)}).")
        for section in fund_data["sections"]:
            seen = set()
            for member in section["members"]:
                slug = member.get("slug")
                key = (fund, section["title"], slug)
                if key in seen:
                    sys.exit(f"ERROR: duplicate (fund, section, slug) in roster: {key}")
                seen.add(key)
                if not slug or slug not in people:
                    sys.exit(f"ERROR: roster slug '{slug}' (fund '{fund}', section '{section['title']}') does not resolve to a person.")
                person = people[slug]
                if not person.get("funds", {}).get(fund, {}).get("assigned"):
                    sys.exit(f"ERROR: '{slug}' is not assigned to fund '{fund}' in the person directory; refusing to render a blank card.")
                if not (member.get("title") or "").strip():
                    sys.exit(f"ERROR: roster member '{slug}' (fund '{fund}', section '{section['title']}') has an empty title.")


def main():
    parser = argparse.ArgumentParser(
        description="Render Taranis fund-team cards from taranis-fund-teams.json."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify pages are already in sync; exit 1 if any would change (no writes).",
    )
    args = parser.parse_args()

    roster = load_roster()
    people = load_people()
    validate(roster, people)

    out_of_sync = []
    written = []
    for fund, path in SUBDOMAIN_PAGES.items():
        if fund not in roster:
            print(f"  {'-- ':7} {fund}: not in roster, skipped")
            continue
        fund_data = roster[fund]
        block = build_block(fund_data, people, fund)
        n_sections = len(fund_data["sections"])
        n_cards = sum(len(s["members"]) for s in fund_data["sections"])
        label = str(path.relative_to(REPO_ROOT)).replace("\\", "/")
        changed, out_bytes = rewrite(path, block)
        detail = f"({n_sections} section{'s' if n_sections != 1 else ''}, {n_cards} card{'s' if n_cards != 1 else ''})"
        if args.check:
            if changed:
                out_of_sync.append(label)
            print(f"  {'DRIFT ' if changed else 'ok    '} {label}  {detail}")
        else:
            if changed:
                path.write_bytes(out_bytes)
                written.append(label)
            print(f"  {'updated' if changed else 'nochange'}  {label}  {detail}")

    print()
    if args.check:
        if out_of_sync:
            print(f"OUT OF SYNC: {len(out_of_sync)} page(s) would change. Run: python tools/build-people.py")
            sys.exit(1)
        print("All team sections are in sync with taranis-fund-teams.json.")
        return

    if written:
        print("Stage with:")
        print("  git add taranis-fund-teams.json " + " ".join(written))
    else:
        print("No changes - all pages already match taranis-fund-teams.json.")


if __name__ == "__main__":
    main()
